# Image repositories for automated updates
# Flux will scan these registries for new images
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cs720-frontend
  namespace: flux-system
spec:
  image: ghcr.io/script-repo/cs720-frontend
  interval: 5m0s
  # secretRef:
  #   name: ghcr-auth  # Uncomment for private repos
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cs720-backend
  namespace: flux-system
spec:
  image: ghcr.io/script-repo/cs720-backend
  interval: 5m0s
  # secretRef:
  #   name: ghcr-auth  # Uncomment for private repos
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cs720-proxy
  namespace: flux-system
spec:
  image: ghcr.io/script-repo/cs720-proxy
  interval: 5m0s
  # secretRef:
  #   name: ghcr-auth  # Uncomment for private repos
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cs720-ai-service
  namespace: flux-system
spec:
  image: ghcr.io/script-repo/cs720-ai-service
  interval: 5m0s
  # secretRef:
  #   name: ghcr-auth  # Uncomment for private repos
